# Generated by Django 3.1.4 on 2021-05-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('person', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
                ('color', models.CharField(choices=[(None, '-----'), ('black', 'Черный'), ('blue', 'Голубой'), ('yellow', 'Желтый'), ('purple', 'Пурпурный')], default=None, max_length=12, null=True, verbose_name='цвет')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='производитель')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
            },
        ),
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя устройства')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='серийный номер')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='статус')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridgemodel', verbose_name='модель картриджа')),
                ('period_of_product_diagnostics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'катридж',
                'verbose_name_plural': 'катриджи',
            },
        ),
    ]
