# Generated by Django 3.1.4 on 2021-05-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('mainapp', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'модель колонок',
                'verbose_name_plural': 'модели колонок',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя устройства')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='серийный номер')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, verbose_name='cтатус устройства')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.speakersmodel', verbose_name='модель колонок')),
                ('period_of_product_diagnostics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'колонки',
                'verbose_name_plural': 'колонки',
            },
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('diagonal', models.IntegerField(verbose_name='диоганаль')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'модель монитора',
                'verbose_name_plural': 'модели мониторов',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя устройства')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='серийный номер')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, verbose_name='cтатус устройства')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.monitormodel', verbose_name='модель монитора')),
                ('period_of_product_diagnostics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'монитор',
                'verbose_name_plural': 'мониторы',
            },
        ),
        migrations.CreateModel(
            name='HeadsetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'модель гарнитуры',
                'verbose_name_plural': 'модели гарнитур',
            },
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя устройства')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='серийный номер')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, verbose_name='cтатус устройства')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.headsetmodel', verbose_name='модель гарнитуры')),
                ('period_of_product_diagnostics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'гарнитура',
                'verbose_name_plural': 'гарнитуры',
            },
        ),
    ]
