# Generated by Django 3.1.4 on 2021-04-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название должности')),
                ('leader', models.BooleanField(default=False, verbose_name='Руководитель')),
                ('vip', models.BooleanField(default=False, verbose_name='Vip-персонал')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('lastName', models.CharField(max_length=100, verbose_name='Имя')),
                ('fatherName', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл.почта')),
                ('workPhone', models.CharField(max_length=3, verbose_name='Рабочий телефон')),
                ('mobilePhone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Мобильный телефон')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.department', verbose_name='Отдел')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.position', verbose_name='Должность')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
