# Generated by Django 3.1.4 on 2021-04-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210403_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='leader',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название должности'),
        ),
        migrations.AlterField(
            model_name='position',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='Vip-персонал'),
        ),
    ]
