# Generated by Django 3.1.4 on 2021-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobilePhone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Мобильный телефон'),
        ),
        migrations.AddField(
            model_name='person',
            name='workPhone',
            field=models.CharField(default=1, max_length=3, verbose_name='Рабочий телефон'),
            preserve_default=False,
        ),
    ]
