# Generated by Django 3.1.4 on 2021-04-03 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20210403_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
    ]
