# Generated by Django 3.1.4 on 2021-04-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_remove_position_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.department', verbose_name='Отдел'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.position', verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
