# Generated by Django 3.1.4 on 2021-05-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('mainapp', '0001_initial'),
        ('locations', '0001_initial'),
        ('cartridges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Статус')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Статус принтера',
                'verbose_name_plural': 'Статусы принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Тип принтера',
                'verbose_name_plural': 'Типы принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printertype', verbose_name='Тип принтера')),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модели принтеров',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='имя устройства')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='серийный номер')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('ip', models.CharField(max_length=15, verbose_name='ip адресc')),
                ('black_cartridge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_cartridge', to='cartridges.cartridge', verbose_name='черный картридж')),
                ('blue_cartridge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_cartridge', to='cartridges.cartridge', verbose_name='голубой картридж')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printermodel', verbose_name='модель принтера')),
                ('period_of_product_diagnostics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
                ('purple_cartridge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purple_cartridge', to='cartridges.cartridge', verbose_name='пурпурный картридж')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.printerstatus', verbose_name='cтатус принтера')),
                ('yellow_cartridge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellow_cartridge', to='cartridges.cartridge', verbose_name='желтый картридж')),
            ],
            options={
                'verbose_name': 'принетер',
                'verbose_name_plural': 'принтеры',
            },
        ),
    ]
