# Generated by Django 3.1.4 on 2021-02-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printermodel',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель'),
        ),
    ]
