# Generated by Django 3.1.4 on 2021-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerscheduler',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
