# Generated by Django 3.1.4 on 2021-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0003_auto_20210311_2029'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='printer',
            field=models.ManyToManyField(blank=True, null=True, to='catriges.Catrige', verbose_name='Установленый картридж'),
        ),
    ]
