# Generated by Django 3.1.4 on 2021-03-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0002_auto_20210318_1142'),
        ('printers', '0002_auto_20210321_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='black_cartridge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='black_cartridge', to='catriges.catrige', verbose_name='Черный картридж'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='blue_cartridge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blue_cartridge', to='catriges.catrige', verbose_name='Голубой картридж'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='purple_cartridge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purple_cartridge', to='catriges.catrige', verbose_name='Пурпурный картридж'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='yellow_cartridge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yellow_cartridge', to='catriges.catrige', verbose_name='Желтый картридж'),
        ),
    ]
