# Generated by Django 3.1.4 on 2021-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0004_auto_20210316_1814'),
        ('printers', '0002_printer_printer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='printer',
        ),
        migrations.AddField(
            model_name='printer',
            name='catridges',
            field=models.ManyToManyField(blank=True, to='catriges.Catrige', verbose_name='Установленый картридж'),
        ),
    ]
