# Generated by Django 3.1.4 on 2021-03-03 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_auto_20210303_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.printerstatus', verbose_name='Статус принтера'),
        ),
    ]
