# Generated by Django 3.1.4 on 2021-04-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель колонок',
                'verbose_name_plural': 'Модели колонок',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.speakersmodel', verbose_name='Динамиков')),
            ],
            options={
                'verbose_name': 'Колонки',
                'verbose_name_plural': 'Колонки',
            },
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('diagonal', models.IntegerField(verbose_name='Диоганаль')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель монитора',
                'verbose_name_plural': 'Модели мониторов',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.monitormodel', verbose_name='Модель монитора')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Мониторы',
            },
        ),
        migrations.CreateModel(
            name='HeadsetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель гарнитуры',
                'verbose_name_plural': 'Модели гарнитур',
            },
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.headsetmodel', verbose_name='Модель гарнитуры')),
            ],
            options={
                'verbose_name': 'Гарнитура',
                'verbose_name_plural': 'Гарнитуры',
            },
        ),
    ]
