# Generated by Django 3.1.4 on 2021-04-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
        ('person', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('number', models.CharField(blank=True, max_length=150, verbose_name='Заявка в тех.поддержку')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Гарнитура',
                'verbose_name_plural': 'Гарнитуры',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('number', models.CharField(blank=True, max_length=150, verbose_name='Заявка в тех.поддержку')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Монитор',
                'verbose_name_plural': 'Мониторы',
            },
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('number', models.CharField(blank=True, max_length=150, verbose_name='Заявка в тех.поддержку')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Колонки',
                'verbose_name_plural': 'Колонки',
            },
        ),
        migrations.CreateModel(
            name='SpeakersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель колонок',
                'verbose_name_plural': 'Модели колонок',
            },
        ),
        migrations.CreateModel(
            name='SpeakerScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Место расположение')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.speakers', verbose_name='Колонки')),
            ],
            options={
                'verbose_name': 'Журнал колонок',
                'verbose_name_plural': 'Журналы колонок',
            },
        ),
        migrations.AddField(
            model_name='speakers',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.speakersmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='period_of_product_diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='MonitorScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Место расположение')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.monitor', verbose_name='Монитор')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал мониторов',
                'verbose_name_plural': 'Журналы мониторов',
            },
        ),
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('diagonal', models.IntegerField(verbose_name='Диоганаль')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель монитора',
                'verbose_name_plural': 'Модели мониторов',
            },
        ),
        migrations.AddField(
            model_name='monitor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.monitormodel', verbose_name='Модель монитора'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='period_of_product_diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='HeadsetScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('headset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.headset', verbose_name='Наушники')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Место расположение')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал гарнитур',
                'verbose_name_plural': 'Журналы гарнитур',
            },
        ),
        migrations.CreateModel(
            name='HeadsetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель гарнитуры',
                'verbose_name_plural': 'Модели гарнитур',
            },
        ),
        migrations.AddField(
            model_name='headset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outputs.headsetmodel', verbose_name='Модель гарнитуры'),
        ),
        migrations.AddField(
            model_name='headset',
            name='period_of_product_diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики'),
        ),
        migrations.AddField(
            model_name='headset',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь'),
        ),
    ]
