# Generated by Django 3.1.4 on 2021-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0002_auto_20210420_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorscheduler',
            name='monitorStatus',
        ),
        migrations.AddField(
            model_name='headset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='monitorscheduler',
            name='status',
            field=models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status',
            field=models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='StatusOutputs',
        ),
    ]
