# Generated by Django 3.1.4 on 2021-04-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0003_auto_20210424_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headset',
            name='date_of_planned_diagnostics',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='date_of_planned_diagnostics',
        ),
        migrations.RemoveField(
            model_name='speakers',
            name='date_of_planned_diagnostics',
        ),
    ]
