# Generated by Django 3.1.4 on 2021-05-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tituls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=4, verbose_name='Номер титула')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название титула')),
            ],
            options={
                'verbose_name': 'Титул',
                'verbose_name_plural': 'Титулы',
                'db_table': 'Tituls',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('titul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.tituls', verbose_name='Титул')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'db_table': 'Room',
            },
        ),
    ]
