# Generated by Django 3.1.4 on 2021-05-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('devices', '0001_initial'),
        ('locations', '0001_initial'),
        ('printers', '0001_initial'),
        ('cartridges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakersScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='cтатус')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.speakers', verbose_name='колонки')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'журнал колонки',
                'verbose_name_plural': 'журналы колонок',
            },
        ),
        migrations.CreateModel(
            name='PrinterScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printer', verbose_name='принтер')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printers.printerstatus', verbose_name='статус принетра')),
            ],
            options={
                'verbose_name': 'журнал принтера',
                'verbose_name_plural': 'журналы принтеров',
            },
        ),
        migrations.CreateModel(
            name='MonitorScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='cтатус')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.monitor', verbose_name='монитор')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'журнал монитора',
                'verbose_name_plural': 'журналы мониторов',
            },
        ),
        migrations.CreateModel(
            name='HeadsetScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('repair', 'На ремонт')], default='reserved', max_length=12, null=True, verbose_name='cтатус')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.headset', verbose_name='гарнитура')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'журнал гарнитуры',
                'verbose_name_plural': 'журналы гарнитур',
            },
        ),
        migrations.CreateModel(
            name='CartridgeScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='cтатус')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartridges.cartridge', verbose_name='картридж')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'журнал картриджа',
                'verbose_name_plural': 'журналы картриджей',
            },
        ),
    ]
