# Generated by Django 3.1.4 on 2021-05-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartridgescheduler',
            old_name='device',
            new_name='cartridge',
        ),
        migrations.RenameField(
            model_name='headsetscheduler',
            old_name='device',
            new_name='headset',
        ),
        migrations.RenameField(
            model_name='monitorscheduler',
            old_name='device',
            new_name='monitor',
        ),
        migrations.RenameField(
            model_name='printerscheduler',
            old_name='device',
            new_name='printer',
        ),
        migrations.RenameField(
            model_name='speakersscheduler',
            old_name='device',
            new_name='speakers',
        ),
    ]
