# Generated by Django 3.1.4 on 2021-03-27 20:51

import catriges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('color', models.CharField(choices=[(None, '-----'), ('black', 'Черный'), ('blue', 'Голубой'), ('yellow', 'Желтый'), ('purple', 'Пурпурный')], default=None, max_length=12, null=True, verbose_name='Цвет')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
            },
        ),
        migrations.CreateModel(
            name='Catrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('catrigeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.cartridgemodel', verbose_name='Модель картриджа')),
            ],
            options={
                'verbose_name': 'Катридж',
                'verbose_name_plural': 'Катриджи',
            },
        ),
        migrations.CreateModel(
            name='CatrigeScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('uuid', models.PositiveSmallIntegerField(default=catriges.models.random_number, verbose_name='Номер заявки')),
                ('catrigeStatus', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('catrige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrige', verbose_name='Картридж')),
            ],
            options={
                'verbose_name': 'Журнал картриджей',
                'verbose_name_plural': 'Журналы картриджей',
            },
        ),
    ]
