# Generated by Django 3.1.4 on 2021-03-08 18:39

import catriges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
            },
        ),
        migrations.CreateModel(
            name='Catrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('catrigeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.cartridgemodel', verbose_name='Модель картриджа')),
            ],
            options={
                'verbose_name': 'Катридж',
                'verbose_name_plural': 'Катриджи',
            },
        ),
        migrations.CreateModel(
            name='CatrigeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Статус')),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Статус картриджа',
                'verbose_name_plural': 'Картриджи',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Цвет')),
                ('word', models.CharField(max_length=1, verbose_name='Обозначение')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='CatrigeScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('uuid', models.PositiveSmallIntegerField(default=catriges.models.random_number, verbose_name='Номер заявки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('catrige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrige', verbose_name='Картридж')),
                ('printerStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catriges.catrigestatus', verbose_name='Статус принетра')),
            ],
            options={
                'verbose_name': 'Журнал картриджей',
                'verbose_name_plural': 'Журналы картриджей',
            },
        ),
        migrations.AddField(
            model_name='catrige',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrigestatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='cartridgemodel',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='cartridgemodel',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель'),
        ),
    ]
