# Generated by Django 3.1.4 on 2021-04-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('mainapp', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('color', models.CharField(choices=[(None, '-----'), ('black', 'Черный'), ('blue', 'Голубой'), ('yellow', 'Желтый'), ('purple', 'Пурпурный')], default=None, max_length=12, null=True, verbose_name='Цвет')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.firm', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Модель картриджа',
                'verbose_name_plural': 'Модели картриджей',
            },
        ),
        migrations.CreateModel(
            name='Catrige',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=30, unique=True, verbose_name='Серийный номер')),
                ('number', models.CharField(blank=True, max_length=150, verbose_name='Заявка в тех.поддержку')),
                ('date_of_planned_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата плановой диагности')),
                ('date_of_last_diagnostics', models.DateField(blank=True, null=True, verbose_name='дата последней диагностики')),
                ('status', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('catrigeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.cartridgemodel', verbose_name='Модель картриджа')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Катридж',
                'verbose_name_plural': 'Катриджи',
            },
        ),
        migrations.CreateModel(
            name='CatrigeScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('catrigeStatus', models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('number', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Заявка в тех.поддержку')),
                ('catrige', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catriges.catrige', verbose_name='Картридж')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал картриджей',
                'verbose_name_plural': 'Журналы картриджей',
            },
        ),
    ]
