# Generated by Django 3.1.4 on 2021-04-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrigescheduler',
            name='number',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Заявка в тех.поддержку'),
        ),
    ]
