# Generated by Django 3.1.4 on 2021-03-10 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catrigescheduler',
            old_name='printerStatus',
            new_name='catrigeStatus',
        ),
    ]
