# Generated by Django 3.1.4 on 2021-04-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('catriges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catrige',
            name='period_of_product_diagnostics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.periodofdiagnostics', verbose_name='период диагностики'),
        ),
    ]
