# Generated by Django 3.1.4 on 2021-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridgemodel',
            name='color',
            field=models.CharField(choices=[(None, '-----'), ('black', 'Черный'), ('blue', 'Голубой'), ('yellow', 'Желтый'), ('purple', 'Пурпурный')], default=None, max_length=12, null=True, verbose_name='Цвет'),
        ),
    ]
