# Generated by Django 3.1.4 on 2021-03-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0002_auto_20210310_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catrigestatus',
            options={'verbose_name': 'Статус картриджа', 'verbose_name_plural': 'Статусы картриджей'},
        ),
    ]
