# Generated by Django 3.1.4 on 2021-03-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0002_auto_20210318_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrige',
            name='status',
            field=models.CharField(choices=[(None, '-----'), ('working', 'В работе'), ('onrefill', 'На заправку'), ('reserved', 'В резерве'), ('purple', 'Пурпурный')], default=None, max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='catrigescheduler',
            name='catrigeStatus',
            field=models.CharField(choices=[(None, '-----'), ('working', 'В работе'), ('onrefill', 'На заправку'), ('reserved', 'В резерве'), ('purple', 'Пурпурный')], default=None, max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='CatrigeStatus',
        ),
    ]
