# Generated by Django 3.1.4 on 2021-04-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0003_catrige_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catrige',
            name='date_of_planned_diagnostics',
        ),
    ]
