# Generated by Django 3.1.4 on 2021-03-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0003_auto_20210322_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrige',
            name='status',
            field=models.CharField(choices=[(None, '-----'), ('working', 'В работе'), ('onrefill', 'На заправку'), ('reserved', 'В резерве')], default=None, max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='catrigescheduler',
            name='catrigeStatus',
            field=models.CharField(choices=[(None, '-----'), ('working', 'В работе'), ('onrefill', 'На заправку'), ('reserved', 'В резерве')], default=None, max_length=12, null=True, verbose_name='Статус'),
        ),
    ]
