# Generated by Django 3.1.4 on 2021-04-03 08:34

from django.db import migrations, models
import django.db.models.deletion
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20210403_1026'),
        ('catriges', '0003_catrigescheduler_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrigescheduler',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catrigescheduler',
            name='person',
            field=models.ForeignKey(blank=True, default=person.models.Person, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Пользователь'),
        ),
    ]
