# Generated by Django 3.1.4 on 2021-03-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0003_auto_20210311_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridgemodel',
            name='color',
            field=models.CharField(choices=[(None, '-----'), ('black', 'Черный'), ('red', 'Красный'), ('blue', 'Синий'), ('yellow', 'Желтый')], default=None, max_length=12, null=True, verbose_name='Цвет'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
