# Generated by Django 3.1.4 on 2021-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0004_auto_20210403_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrigescheduler',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
