# Generated by Django 3.1.4 on 2021-03-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catriges', '0004_auto_20210322_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catrige',
            name='status',
            field=models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='catrigescheduler',
            name='catrigeStatus',
            field=models.CharField(choices=[('reserved', 'В резерве'), ('working', 'В работе'), ('onrefill', 'На заправку')], default='reserved', max_length=12, null=True, verbose_name='Статус'),
        ),
    ]
